apiVersion: v1
kind: LoadBalancer
metadata:
  name: play-catalog
spec:
  selector:
    app: play-catalog
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000 # your container listens on 5000
  type: ClusterIP
